all: pa2 pwd rm mv cp cat head tail

pa2: minishell.c
	gcc -o pa2 minishell.c

pwd: pwd.c
	gcc -o pwd pwd.c

rm: rm.c
	gcc -o rm rm.c

mv: mv.c
	gcc -o mv mv.c

cp: cp.c
	gcc -o cp cp.c

cat: cat.c
	gcc -o cat cat.c

head: head.c
	gcc -o head head.c

tail: tail.c
	gcc -o tail tail.c

clean:
	rm pa2 pwd rm mv cp cat head tail